[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
caliber_escrow = "2HLurVWnnxMYj7xfvSKasKUVWcirE33hXY3fd7rFu4fm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
